### ISSUE TITLE
订阅更新失败

### ISSUE THREAD

**Issue by LilJohn419** [yaof2/luci-app-ikoolproxy#103]
以下三条更新失败
	wget 'https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/kp.dat' -q -O $KP_DIR/data/rules/kp.dat
	wget 'https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/daily.txt' -q -O $KP_DIR/data/rules/daily.txt
	wget 'https://yaof.coding.net/p/ikoolproxy/d/rules/git/raw/master/rules/koolproxy.txt' -q -O $KP_DIR/data/rules/koolproxy.txt

**Comment by yaof2** [comment]
上游houzi-主机打不开。晚点再试试
