### ISSUE TITLE
发现luci列表无法应用

### ISSUE THREAD

**Issue by gzsdbb** [yaof2/luci-app-ikoolproxy#106]
在luci界面中无论是网站白名单设置、网站黑名单设置、IP白名单设置、IP黑名单设置、自定义规则 

点保存和应该都会提示“没有待应用的更改” 但相应的文件已经写入完成 只有重启插件才能应用

另 这些列表一但修改  无法有luci中清空 只能到对应文件中删除

**Comment by yaof2** [comment]
我自己编译的，好像没有你反应的问题哦
