### ISSUE TITLE
每天凌晨4、5点更新很多规则更新失败

### ISSUE THREAD

**Issue by tonyliangli** [yaof2/luci-app-ikoolproxy#110]
我设置凌晨4点或5点自动更新，白天看界面上很多规则都是0条，只有个别规则更新成功，日志里也没出现更新失败的规则日期。

**Comment by yaof2** [comment]
上游规则每个礼拜更新一回，没有必要开启每天更新一次。估计是coding限制了并发数，手动更新吧
