### ISSUE TITLE
CONFIG_PACKAGE_koolproxy=y

### ISSUE THREAD

**Issue by exlulu** [yaof2/luci-app-ikoolproxy#116]
不知道是否有意改变，以前是CONFIG_PACKAGE_**i**koolproxy，是以后都是CONFIG_PACKAGE_koolproxy吗？因为要使用Actions，希望不要变来变去，不然每次运行Actions前要先导出配置检查

**Comment by yaof2** [comment]
CONFIG_PACKAGE_ikoolproxy=y

**Comment by exlulu** [comment]
> CONFIG_PACKAGE_ikoolproxy=y

现在是这样
CONFIG_PACKAGE_koolproxy=y
CONFIG_PACKAGE_luci-app-ikoolproxy=y

以前是这样
CONFIG_PACKAGE_**_i_**koolproxy=y
CONFIG_PACKAGE_luci-app-ikoolproxy=y
