### ISSUE TITLE
koolproxy  这个文件换位置了么？云编译老是在这里失败。

### ISSUE THREAD

**Issue by jikkyfu** [yaof2/luci-app-ikoolproxy#119]
* pkg_hash_check_unresolved: cannot find dependency koolproxy for luci-app-ikoolproxy
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-ikoolproxy found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-ikoolproxy.

**Comment by yaof2** [comment]
没有。看下Makefile。自动依赖koolproxy
