### ISSUE TITLE
规则更新地址失效

### ISSUE THREAD

**Issue by exlulu** [yaof2/luci-app-ikoolproxy#124]
全都显示
`{"msg":{"user_not_login":"用户未登录"},"data":{"account_type":"0"},"code":1000}`

**Comment by yaof2** [comment]
coding规则地址，不知道试试最近敏感时期，等过了几天再试试。临时解决需要自己动手，换个地址：winscp登陆路由器，找到/usr/share/koolproxy下的kpupdate。找到“内置规则更新”将地址更改即可。地址https://github.com/yaof2/koolproxy 这里的地址2和3都可以。

**Comment by yaof2** [comment]
已经修复。
