### ISSUE TITLE
内核版本问题

### ISSUE THREAD

**Issue by xdfx1180** [yaof2/luci-app-ikoolproxy#125]
由于本项目不支持5.10以上的内核版本，老大能否把本项目弄个docker版本，这样就对内核版本没什么要求了，感谢！！！

**Comment by dlg800** [comment]
大佬，x86的op上一开ikoolp就显示不能运行且断网，关闭它网络恢复！

**Comment by yaof2** [comment]
不支持5.4以上的内核
